name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Build production bundle
      run: yarn build
    - name: Run linter
      run: yarn lint